(function(g){var window=this;var s4=function(a){var b={format:a.B,languageCode:a.A,languageName:a.D,displayName:g.YH(a),kind:a.C,name:a.F,id:a.Ia,is_servable:a.M,is_default:a.isDefault,is_translateable:a.H,vss_id:a.G};a.o&&(a=a.o,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.o,id:a.id,is_default:a.isDefault});return b},t4=function(a){return a.o?a.o.languageCode:a.A},fBa=function(a,b){var c=new g.XH;
c.A=a.A;c.D=a.D;c.F=a.F;c.C=a.C;c.isDefault=!1;c.H=a.H;c.G=a.G;c.J=a.J;c.o=b;return c},u4=function(a){return(a=g.bU(a.app,void 0))?a.J?a.J.C:0:0},v4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.uQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},w4=function(a,b,c,d,e){g.uQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},y4=function(a){a=void 0===a?{}:a;
var b="_"+x4++;return new w4(0,0x8000000000000,0,b,a)},z4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.qb);a.params.qb&&g.Ga(l,a.params.qb);g.Ga(l,c.qb);k.qb=l;g.W.call(this,{I:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.Wk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},P:[{I:"span",N:"captions-text"}]});this.D=[];this.M=!1;this.H=a;this.G=[];this.J=[];this.Ba=e;this.za=f;this.F=null;this.aa=.96*e;this.ka=.96*f;this.A=k;this.va=c;this.C=this.o["captions-text"];this.na=null!=this.C.style["box-decoration-break"]||
null!=this.C.style["-webkit-box-decoration-break"];this.O=d/360*16;this.type=0;this.ga=this.O*gBa(l);a=new g.VF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.NP,this);a.subscribe("dragmove",this.MP,this);a.subscribe("dragend",this.LP,this);this.ia=this.ha=0;a="";this.A.windowOpacity&&(a=g.Et(this.A.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.A.windowOpacity+")");b={"background-color":a,display:!1===this.A.isVisible?"none":"","text-align":hBa[this.A.textAlign]};this.na&&(b["border-radius"]=
a?this.ga/8+"px":"");g.xh(this.element,b);switch(this.A.Qf){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},gBa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},A4=function(a,b){var c={},d=b.background?b.background:a.A.qb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.A.qb.backgroundOpacity;d=g.Et(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.na&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.O*gBa(b)+"px";d=1;e=b.color||a.A.qb.color;if(b.color||null!=b.textOpacity)e=g.Et(e),d=null==b.textOpacity?a.A.qb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Iy&&(k=e=b.Iy);var l=a.O/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.HE()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.A.qb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.zf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.lt&&(c.visibility="hidden");return c},iBa=function(a,b,c){a.M=a.M||!!c;
var d={};g.Ga(d,a.A.qb);g.Ga(d,c||b.A);g.Ga(d,a.va.qb);c=a.G[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.lt==!!c.lt&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.G.length;e++)if(g.dc(d,a.G[e])){var f=a.J[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Ld("SPAN");g.xh(f,A4(a,e));a.J[0].appendChild(f);e=1}a.J.length=e;a.G.length=e}else a.J.length=0,a.G.length=0,f=g.Ld("SPAN"),g.xh(f,A4(a,d)),a.C.appendChild(f);a.F&&a.F.parentNode!=f&&(g.Rd(a.F),
f.appendChild(a.F));c=(k=g.w(b.text))?b.text.split("\n"):[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.D.length||!b.D){if(0<e||0!=a.D.length){var m=g.Ld("BR");f.appendChild(m)}f.appendChild(g.Md("\u00a0"));a.F=g.Md("\u00a0");f.appendChild(a.F)}l&&(m=a.F,m.parentNode&&m.parentNode.insertBefore(k?g.Md(l):l,m))}a.G.push(d);a.J.push(f);a.D.push(b)},jBa=function(){},C4=function(){this.C=this.A=this.mode=this.B=0;
this.D=new B4(this);this.F=new B4(this);this.o=[];this.clear()},lBa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Un:a,
Vn:b,result:0};a=kBa[a];b=kBa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Un:a,Vn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Un:a,Vn:b,result:2};return{Un:a,Vn:b,result:3}},nBa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.C&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.C=0,mBa(a.D,b,c,d))},oBa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?nBa(a,d.Dy,d.Ey,b):1==d.type&&a.B&496&&mBa(a.F,d.Dy,d.Ey,b)}a.o.length=0},D4=function(){this.o=0},E4=function(){this.A=this.B=this.o=0},F4=function(){this.timestamp=this.Ee=0},G4=function(a){this.B=[];
for(var b=0;15>=b;b++){this.B[b]=[];for(var c=0;32>=c;c++)this.B[b][c]=new F4}this.o=this.A=this.row=0;this.style=new D4;this.D=a;this.C=0},H4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!=r.Ee){0==c&&(c=m,d=p);n=String.fromCharCode(r.Ee);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Ee||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],r=p.Ee,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},tBa=function(a,b){switch(a){case 0:return pBa[(b&127)-32];
case 1:return qBa[b&15];case 2:return rBa[b&31];case 3:return sBa[b&31]}return 0},I4=function(a){return a.B[a.row][a.A]},J4=function(a,b,c){2<=b&&1<a.A&&(--a.A,I4(a).Ee=0);
var d=I4(a);d.timestamp=a.D.A+0;d.Ee=tBa(b,c);32>a.A&&a.A++},uBa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.B[b+e][f].no(a.B[c+e][f])},K4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},L4=function(a){a.row=0<a.o?a.o:1;
a.A=1;K4(a,0,15)},M4=function(a){this.C=a;
this.D=0;this.style=new D4;this.F=new G4(a);this.G=new G4(a);this.H=new G4(a);this.A=this.F;this.B=this.G;this.o=this.A},N4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:H4(d,c),L4(a.A),L4(a.B),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.C.mode=1<<d.C;e?d.A=1:d.o!=b&&(d.o>b?(H4(d,c),K4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},vBa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.C.mode=1<<a.o.C},wBa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.C.mode=1<<a.o.C},B4=function(a){this.A=a;
this.o=new E4;this.D=0;this.B=new M4(a);this.F=new M4(a);this.C=this.B},mBa=function(a,b,c,d){a.o.update();
b=lBa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Un;c=b.Vn;if(32<=e||!e)a.A.mode&a.A.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.o,b&96&&J4(a,0,b),c&96&&J4(a,0,c),0!=b&&0!=c&&3==a.style.o&&H4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.B=e,b.A=c,b.o=2,b=e&8?a.F:a.B,a.C=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;uBa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));K4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:J4(b.o,0,32);break a;case 48:57==c?(b=b.o,I4(b).Ee=0,32>b.A&&b.A++):J4(b.o,1,c&15)}break;case 2:c&32&&J4(b.o,2,c&31);break;case 3:c&32&&J4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:vBa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,I4(b).Ee=0);break;case 36:b=b.o;d=I4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.B[a][c]==d){for(;32>=c;c++)b.B[a][c].reset();break}break;case 37:N4(b,2,d);break;case 38:N4(b,3,d);break;case 39:N4(b,4,d);break;case 40:J4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.C.mode=1<<b.o.C;break;case 42:d=b.H;d.o=15;d.style.set(4);L4(d);wBa(b);break;case 43:wBa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:H4(a,d)}K4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;H4(a,d);uBa(a,b,b+1,a.o-1);K4(a,a.row,1)}break;case 46:K4(b.B,0,15);break;case 47:H4(b.A,d);d=b.B;a=b.C.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.B[c][e].timestamp=a;d=b.B;b.B=b.A;b.A=d;vBa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},O4=function(){},P4=function(a){this.A=a;
this.o=null},yBa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.fs("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");xBa(d,e,k,b,f,a.firstChild,{},c)},xBa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.zf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");Q4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new v4(a,b,c,d,n.nodeValue,e||0<m,g.$b(k)?void 0:k));else{var p={};g.Ga(p,k);xBa(a,b,c,d,e||0<m,n,p,l)}}},R4=function(){this.A={};
this.o=null},S4=function(a){this.C={};
this.J={};this.K={};this.D="_"+x4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},T4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},U4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},V4=function(a,b){var c=T4(a,b);
if(void 0!=c)return c},W4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Q4.test(c),c},zBa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.K[d]:a.F);d=V4(b,"mh");null!=d&&(c.nu=d);d=V4(b,"ju");null!=d&&(c.textAlign=d);d=V4(b,"pd");null!=d&&(c.Wk=d);d=W4(b,"wfc");null!=d&&(c.windowColor=d);d=T4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},ABa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.J[d]);d=V4(b,"ap");null!=d&&(c.Qf=d);d=T4(b,"cc");null!=d&&(c.Zr=d);d=T4(b,"ah");null!=d&&(c.bf=d);d=T4(b,"rc");null!=d&&(c.uq=d);d=T4(b,"av");null!=d&&(c.wg=d);return c},BBa=function(a,b,c,d){var e={};
g.Ga(e,ABa(a,b));g.Ga(e,zBa(a,b));d?g.dc(e,a.F)?(d=a.D,e=a.F):d="_"+x4++:d=b.getAttribute("id")||"_"+x4++;a=T4(b,"t")+c;b=T4(b,"d")||0x8000000000000;return new w4(a,b,0,d,e)},X4=function(a,b,c){this.G=c;
this.version=this.F=this.C=this.o=0;this.A=new window.DataView(a);this.B=[]},Y4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},Z4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},$4=function(a,b){this.A=a;
this.track="CC3"==b.D?4:0;this.o=new C4;this.o.B=1<<this.track},DBa=function(a){if(g.w(a))return!1;
a=new X4(a,8,0);return CBa(a)},CBa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=Z4(a))return!1;
a.version=Y4(a);if(1<a.version)return!1;Y4(a);Y4(a);Y4(a);return!0},EBa=function(){this.A=[];
this.o=[]},a5=function(a,b){return b?a.o.concat(a.A):a.o},b5=function(a,b){switch(b.C){case "asr":var c=a.A;
g.La(c,(0,g.A)(b.K,b))||c.push(b);break;default:c=a.o,g.La(c,(0,g.A)(b.K,b))||c.push(b)}},c5=function(){},FBa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.zf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new v4(b,c,d,e.id,p.nodeValue,f||0<n,g.$b(l)?void 0:l),m.push(p),e.A.push(p);else{var r={};g.Ga(r,l);FBa(a,b,c,d,e,!0,p,r,m)}}},d5=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},GBa=function(a,b,c,d){d=Object.assign({nu:0},d);
return new w4(a,b,c,"_"+x4++,d)},e5=function(a){g.M.call(this);
this.KA=!!a;this.A=new EBa;this.G=[];this.o=null},IBa=function(a){var b={};
if(a=t4(a))b.lang=a,HBa.test(a)&&(b.Wk=1);return b},JBa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.w(b)){var f=new window.DataView(b);if(1718909296==f.getUint32(4)&&(f=g.MJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),!DBa(b)&&(b=g.le(new window.Uint8Array(b)),!b)))return[]}if(g.w(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new c5),a.o.B(b,d);b=g.fs(b);if(!b||!b.firstChild)return[];if(!a.o)if("timedtext"==b.firstChild.tagName)3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new S4(IBa(c)):a.o=new R4;else try{return a.o=new P4(IBa(c)),a.o.B(b,d)}catch(k){return g.cE(k),
a.o=null,[]}return a.o.B(b,d)}try{if(DBa(b))return a.o||(a.o=new $4(e,c)),a.o.B(b,d)}catch(k){g.cE(k),a.o=null}return[]},f5=function(a){e5.call(this,a.bo);
this.C=void 0;this.B=null;this.G=a.captionTranslationLanguages},g5=function(){this.wb=[]},h5=function(a,b,c,d,e,f){g.M.call(this);
this.L=a;this.C=b;this.F=new g5;this.o=null;this.J=d;this.M=f;this.B=this.A=null;this.H=c;this.G=e||!1;this.K=new g.ju(this.fB,1E3,this);g.N(this,this.K);this.D=new g.QF(this);g.N(this,this.D);this.D.R(b,"seekto",this.jC);this.jC(b.getCurrentTime());this.fB()},KBa=function(a,b){b-=u4(a.C);
var c=a.o;a.o=g.Ja(a.H.Hg(b).o);c!=a.o&&a.M&&a.M()},LBa=function(a,b){var c=g.fL(b,a.L,{}).Wa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.B=g.VE(c,d,3,100).then((0,g.A)(a.vU,a));a.A=b;c=a.F;d=a.A.o[0].ya;var e=g.eb(c.wb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.wb[e-1]&&e<c.wb.length&&1==c.wb[e]-d?(g.Ta(c.wb,e),g.Ta(c.wb,e-1)):0<e&&1==d-c.wb[e-1]?c.wb[e-1]=d:e<c.wb.length&&1==c.wb[e]-d?c.wb[e]=d:(g.ab(c.wb,e,0,d),g.ab(c.wb,e+1,0,d)))},i5=function(a,b){e5.call(this);
this.B=a;this.C=b;this.D=null;this.F=!1},MBa=function(a,b){if(b in a.B.o)return a.B.o[b];
if(g.HL(a.B))for(var c in a.B.o){var d=a.B.o[c];if(g.oI(d.info.mimeType)&&("386"!=c||!g.Y(a.C).experiments.o("html5_manifestless_captions_fmt3_killswitch")))return d}return null},j5=function(a,b){return a.Fa&&null!=a.pa||g.Y(b).Na&&null!=a.pa&&null!=a.pa.o.rawcc},k5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
this.type=1},l5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.U=0;this.Z=this.K=window.NaN;this.sa=null;this.da=new g.ju(this.AU,433,this);g.N(this,this.da)},m5=function(a){if(!a.U){var b=g.Ld("SPAN");
g.xh(b,A4(a,a.A.qb));a.C.appendChild(b);b.appendChild(g.Md("M"));var c=b.offsetHeight,d=g.Ld("BR");b.appendChild(d);b.appendChild(g.Md("M"));a.U=b.offsetHeight-c;a.C.removeChild(b)}return a.U},NBa=function(a){if((0,window.isNaN)(a.K)){var b=a.A.Zr;
if(b){var c=g.Ld("SPAN");g.$d(c,"\u2013".repeat(b));g.xh(c,A4(a,a.A.qb));a.C.appendChild(c);a.K=c.offsetWidth;a.C.removeChild(c)}else a.K=0}return a.K},n5=function(a,b,c,d){e5.call(this,d);
c=c||g.oE(a).hl||"";c=c.split("_").join("-");this.D=g.qE(a,{hl:c});this.C=b;this.F={};this.B=null},q5=function(a){g.DU.call(this,a);
this.C=g.Y(a);this.B=a.getVideoData();this.na=g.dU(a);this.K=a;var b=null,c=g.zD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.iD(c));this.aa=b;this.F={qb:{}};this.H={qb:{}};this.O=[];this.U={};this.ba={};this.M=!1;this.sa="1"==this.B.qc.cc_auto_caps||"1"==this.C.fc.cc_auto_caps;b="3"==this.C.C&&!!g.wU(a)&&g.wU(a).kn();this.G=(c=!this.C.experiments.o("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.B.Fa:b;this.ia=c&&b&&this.B.Fa&&j5(this.B,this.K);c=b=this.A=this.D=
this.J=this.L=this.Z=this.ka=null;this.G||(b=new g.gu(this.QF,void 0,this),g.N(this,b),c=new g.ju(this.iW,2E3,this),g.N(this,c));this.da=b;this.ha=c;this.Y=new g.QF(this);g.N(this,this.Y);this.G||this.Y.R(a,"resize",this.ww);this.Y.R(a,"onPlaybackAudioChange",this.uR);this.Y.R(a,"crn_captions",this.NN,this);this.Y.R(a,"crx_captions",this.ON,this);o5(this,p5(this,"display-settings")||{})},OBa=function(a){if(1==a.C.nh||1==a.B.nh||"alwayson"==g.WO(a.B,"yt:cc"))return!0;
if(2==a.C.nh){var b=p5(a,"module-enabled");if(null!=b)return!!b}if(a.B.captionTracks.length)var c=a.o.getAudioTrack().Sr;return"ON"==c||"on"==g.WO(a.B,"yt:cc")},r5=function(a,b){if(a.A&&(void 0===b||!b)||!a.B.captionTracks.length)return!1;
var c=a.o.getAudioTrack();return!!c.Eo||"FORCED_ON"==c.Sr},t5=function(a,b){if(a.D){var c=a5(a.D.A,b||a.sa);
if(a.J&&a.J.o)return a.J.o;for(var d=[a.B.mh,a.C.mh,g.WO(a.B,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(t4(c[f])==d[e])return c[f];return a.J&&a.J.rs?a.J.rs:(d=c.find(function(a){return a.isDefault}))?d:c[0]||s5(a)}return null},s5=function(a){return a.J&&a.J.Eo},PBa=function(a,b){for(var c=g.wU(a.K).oa().textTracks,d=a.A.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},v5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&u5(a,"module-enabled",!!b));a.A=b;r5(a)&&(a.A=s5(a));a.load(d)},QBa=function(a){if(a.A!=s5(a)){if(a.M&&!g.LM(a.C)&&!g.TM(a.C)){g.mu(a.ha);
var b=y4({Qf:0,bf:5,wg:5,uq:2,textAlign:0,Wk:0,lang:"en"});a.Z=[b];var c=["Click "," for settings"];if(!a.ka){var d=new g.AH(g.zqa());g.N(a,d);a.ka=d.element}d=b.end-b.start;var e=g.YH(a.A);e&&a.Z.push(new v4(b.start,d,0,b.id,e));a.Z.push(new v4(b.start,d,0,b.id,c[0]),new v4(b.start,d,0,b.id,a.ka,!0),new v4(b.start,d,0,b.id,c[1],!0));g.qU(a.o,a.Z);g.ku(a.ha)}if(a.M||g.LM(a.C))u5(a,"module-enabled",!0),a.J&&(a.J.o=a.A);(a=g.bU(a.o.app))&&a.C&&g.mP(a.C.B)}},RBa=function(a,b){var c=g.p_(a.na,!0).height;
if(!c)return null;var d=a.na.Ua();switch(null!=b.params.nu?b.params.nu:b.params.UW?2:1<b.A.length?1:0){case 1:return new k5(b,a.F,a.H,c,d.width,d.height);case 2:return new l5(b,a.F,a.H,c,d.width,d.height);default:return new z4(b,a.F,a.H,c,d.width,d.height)}},o5=function(a,b,c){var d=w5.qb;
a.F={};g.Ga(a.F,w5);a.F.qb={};g.Ga(a.F.qb,d);a.H={qb:{}};var e=b.backgroundOverride?a.H:a.F,f=b.background||d.background;Q4.test(f);e.qb.background=f;e=b.colorOverride?a.H:a.F;f=b.color||d.color;Q4.test(f);e.qb.color=f;e=b.windowColorOverride?a.H:a.F;f=b.windowColor||w5.windowColor;Q4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.F;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.qb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.H:a.F;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.qb.fontSizeIncrement=f;f=b.fontStyleOverride?a.H:a.F;e=b.fontStyle;null==e&&(e=d.bold&&d.zf?3:d.bold?1:d.zf?2:0);f=f.qb;switch(e){case 1:f.bold=!0;delete f.zf;break;case 2:delete f.bold;f.zf=!0;break;case 3:f.bold=!0;f.zf=!0;break;default:delete f.bold,delete f.zf}e=b.textOpacityOverride?a.H:a.F;f=b.textOpacity;null==f&&(f=d.textOpacity);e.qb.textOpacity=f;e=b.windowOpacityOverride?a.H:a.F;f=b.windowOpacity;null==f&&(f=w5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.H:a.F;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.qb.charEdgeStyle=f;e=b.fontFamilyOverride?a.H:a.F;f=b.fontFamily;null==f&&(f=d.fontFamily);e.qb.fontFamily=f;a.loaded&&a.ww();c&&u5(a,"display-settings",b)},TBa=function(a,b){if(b&&!a.L){var c=y4({Wk:0,
lang:"en"});a.L=[c,new v4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.qU(a.o,a.L)}else!b&&a.L&&(SBa(a,a.L),a.L=null)},SBa=function(a,b){g.sU(a.o,b);
(0,g.C)(b,function(a){g.Va(this.O,a)},a);
a.da.Zj()},UBa=function(a,b){return a&&g.w(a)&&Q4.test(a)?a:b},VBa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},WBa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.jd(a,-2,4):b},p5=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},u5=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.FQ.prototype.Hj=g.ca(9,function(){for(var a=g.yd(window.document,"track",void 0,this.o),b=0;b<a.length;b++)g.Rd(a[b])});
g.NS.prototype.Hj=g.ca(8,function(){this.o.Hj()});
g.FQ.prototype.kn=g.ca(7,function(){return!!this.o.textTracks});
g.NS.prototype.kn=g.ca(6,function(){return this.o.kn()});
g.FQ.prototype.ol=g.ca(5,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.NS.prototype.ol=g.ca(4,function(a){this.o.ol(a)});
g.rJ.prototype.Oo=g.ca(2,function(a){return(a=this.sh(a))?a.A:0});
g.xL.prototype.Oo=g.ca(1,function(){return 0});
g.XH.prototype.K=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var HBa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Q4=/^#(?:[0-9a-f]{3}){1,2}$/i;var hBa=["left","right","center"];var w5={windowColor:"#080808",windowOpacity:0,textAlign:2,Qf:7,bf:50,wg:100,qb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(v4,g.uQ);g.t(w4,g.uQ);var x4=0;g.t(z4,g.W);g.h=z4.prototype;g.h.NP=function(a,b){var c=g.Oh(this.element,this.element.parentElement);this.ha=a-c.x;this.ia=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.MP=function(a,b){var c=g.Rh(this.element),d=a-this.ha-.02*this.Ba,e=b-this.ia-.02*this.za,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.jd(f,0,2));var k=(e+c.height/2)/this.ka*3;k=Math.floor(g.jd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.jd(d,0,1);c=(e+k/2*c.height)/this.ka;c=100*g.jd(c,0,1);this.H.params.Qf=l;this.H.params.wg=c;this.H.params.bf=d;this.A.Qf=l;this.A.wg=c;this.A.bf=d;this.HE()};
g.h.LP=function(){g.zq(this.element,"ytp-dragging")};
g.h.HE=function(){this.mj(this.D)};
g.h.Ub=function(){return this.type};
g.h.mj=function(a){var b=Math.min(this.Lz(),this.aa),c=this.Kz();g.xh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ir(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.A.bf+2,e=this.A.Qf;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.C.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.A.wg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.xh(this.element,a)};
g.h.Ir=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.M||this.D.length>b)b=0,this.M=!1,this.D=[],this.G=[],this.J=[],this.F=null,g.Pd(this.C);for(;b<a.length;b++)iBa(this,a[b])};
g.h.Lz=function(){return 0};
g.h.Kz=function(){return 0};jBa.prototype.D=function(){};C4.prototype.clear=function(){this.C=this.A=this.mode=0;this.o=[];this.reset()};
C4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var kBa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];D4.prototype.set=function(a){this.o=a};
D4.prototype.get=function(){return this.o};
E4.prototype.clear=function(){this.o=0};
E4.prototype.update=function(){this.o=2==this.o?1:0};
E4.prototype.matches=function(a,b){return 0!=this.o&&a==this.B&&b==this.A};
F4.prototype.no=function(a){this.Ee=a.Ee;this.timestamp=a.timestamp};
F4.prototype.reset=function(){this.timestamp=this.Ee=0};
G4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0==d.Ee?a+"_":a+String.fromCharCode(d.Ee)}a+="\n"}return a};
G4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.o=0;this.A=this.row=1};
var pBa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qBa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rBa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],sBa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];M4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.B=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
B4.prototype.reset=function(a){this.D=a;this.o.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};O4.prototype.reset=function(){};g.t(P4,O4);P4.prototype.B=function(a){var b=[];this.o||(this.o=y4(this.A),b.push(this.o));a=Array.from(a.firstChild.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())yBa(c.value,this.o.id,b);return b};g.t(R4,O4);
R4.prototype.B=function(a){var b=[];this.o||(this.o=y4(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=y4());
var k={};f&&(g.Ga(k,f.params),f=f.params.qb)&&(k.qb={},g.Ga(k.qb,f));e.getAttribute("rc")&&(k.uq=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Zr=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Qf=0>f||8<f?7:f);e.getAttribute("ah")&&(k.bf=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.wg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Wk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Wk=0));e.getAttribute("bc")&&(k.qb||(k.qb={}),k.qb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.qb||(k.qb={}),k.qb.backgroundOpacity=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.qb||(k.qb={}),k.qb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.UW=(0,window.parseInt)(e.getAttribute("sd"),
10));f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+x4++;c=new w4(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],yBa(a,this.o.id,d),d=g.q(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.t(S4,O4);S4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
S4.prototype.B=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Ga(l,this.C[m]);m=U4(c,"b");null!=
m&&(l.bold=m);m=U4(c,"i");null!=m&&(l.zf=m);m=U4(c,"u");null!=m&&(l.underline=m);m=V4(c,"et");null!=m&&(l.charEdgeStyle=m);m=V4(c,"of");null!=m&&(l.offset=m);m=W4(c,"bc");null!=m&&(l.background=m);m=W4(c,"ec");null!=m&&(l.Iy=m);m=W4(c,"fc");null!=m&&(l.color=m);m=V4(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=T4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=T4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);c=T4(c,"fo");void 0!=c&&(l.textOpacity=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");
this.K[d]=zBa(this,c);break;case "wp":d=c.getAttribute("id"),this.J[d]=ABa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=BBa(this,d,e,!1);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!U4(d,"a");n=(T4(d,"t")||0)+n;var p=T4(d,"d")||5E3;m||(!this.G&&this.A&&this.A.windowId==l&&
this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var r=m?6:5,u=this.C[d.getAttribute("p")],E=d.childNodes;E.length&&(this.G=null!=d.getAttribute("d"));for(var H=0;H<E.length;H++){var L=E[H];0<H&&(m=!0);var S=void 0;1==L.nodeType&&(S=L);if(S&&"s"==S.tagName){var fa=S;L=n;S=p;var Ua=l,jb=m,Rc=r,Ge=fa.textContent?fa.textContent:"",ob=this.C[fa.getAttribute("p")];fa=T4(fa,"t")||0;L=new v4(L+fa,S-fa,Rc,Ua,Ge,jb,ob)}else L=new v4(n,p,r,l,L.textContent||"",m,u);k.push(L);this.A=
L}if(0<k.length)for(k[0].windowId==this.D&&(this.o=BBa(this,d,e,!0),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.A.push(k),c.push(k)}e=c}else e=[];return e};g.t(X4,jBa);X4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+x4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new w4(c,d-c,5,f,{textAlign:0,Qf:0,bf:2.5*b,wg:5.33*a});e=new v4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.t($4,O4);$4.prototype.B=function(a){a=new X4(a,a.byteLength,this.A);if(CBa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.C=Z4(a)*(1E3/45):1==a.version&&(a.C=4294967296*Z4(a)+Z4(a)),a.F=Y4(a);0<a.F;a.F--){var b=Y4(a),c=Y4(a),d=Y4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.C,type:this.track,Dy:c,Ey:d,order:b.o.length}))}oBa(this.o,a);return a.B}return[]};
$4.prototype.reset=function(){this.o.clear()};g.t(c5,O4);
c5.prototype.B=function(a,b){for(var c=[],d=a.split(XBa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!YBa.test(f)){var l=x5.exec(f);if(l&&4<=l.length){var m=d5(l[1]),n=d5(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,E=void 0,H=l[3];l={textAlign:2};H=g.q(H?H.split(" "):[]);for(var L=H.next();!L.done;L=H.next())if(L=L.value.split(":"),2==L.length){var S=L[1];switch(L[0]){case "line":L=S.split(",");L[0].endsWith("%")&&(E=L[0],l.wg=Number.parseInt(E,10),2==L.length&&(u=L[1].trim()));break;case "position":L=S.split(",");
r=L[0];l.bf=Number.parseInt(r,10);2==L.length&&(p=L[1].trim());break;case "align":switch(S){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}E||(l.wg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.bf=0;break;case 1:l.bf=100;break;default:l.bf=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Qf=0>r||8<r?7:r;p=l;f=f.substring(x5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=GBa(m,n,5,r),n=new v4(m,n,5,k.id,p,!1,g.$b(f)?void 0:f),c.push(k),c.push(n),k.A.push(n);else for(u=p.split(ZBa),1==u.length?(p=5,r=GBa(m,n,p,r)):(E=p=6,r=Object.assign({Zr:32},r),r=new w4(m,n,E,"_"+x4++,r)),c.push(r),E=m,l=0;l<u.length;l++)H=u[l],0==l%2?(L=g.fs("<html>"+H+"</html>"),L.getElementsByTagName("parsererror").length?
(S=L.createElement("span"),S.appendChild(L.createTextNode(H))):S=L.firstChild,FBa(this,E,n-(E-m),p,r,0<l,S,f,c)):E=d5(H)+k}x5.lastIndex=0}}return c};
var YBa=/^NOTE/,XBa=/(?:\r\n|\r|\n){2,}/,x5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ZBa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(e5,g.M);e5.prototype.trackCount=function(){return a5(this.A,!0).length};
e5.prototype.Wd=function(){this.o=null};
e5.prototype.X=function(){g.M.prototype.X.call(this);this.Wd()};
e5.prototype.oE=function(){return!1};g.t(f5,e5);g.h=f5.prototype;g.h.hu=function(a,b){var c=this.Ol(a),d=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.Wd();this.B=g.yE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.iu=function(a,b,c,d){this.C=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())b5(this.A,c.value);a()};
g.h.Ol=function(a){var b=a.Wa(),c={};if(this.C||a.B)c.fmt=this.C||"srv"+a.B;a.o&&(c.tlang=a.o.languageCode);return g.qE(b,c)};
g.h.Wd=function(){e5.prototype.Wd.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.Wd();e5.prototype.X.call(this)};g5.prototype.contains=function(a){a=g.eb(this.wb,a);return 0<=a||0>a&&1==(-a-1)%2};
g5.prototype.length=function(){return this.wb.length/2};g.t(h5,g.M);g.h=h5.prototype;g.h.X=function(){g.M.prototype.X.call(this);this.B&&this.B.cancel()};
g.h.jC=function(a){var b=this;if(this.H.mk())var c=this.D.R(this.C,"progresssync",function(){b.H.index.Lb()&&(b.reset(),b.o=null,KBa(b,b.C.getCurrentTime()),b.D.Ha(c))});
else KBa(this,a)};
g.h.reset=function(){this.F=new g5;this.B&&(this.B.cancel(),this.B=null)};
g.h.fB=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Rg(a);!a||this.B||this.o&&30<this.o.startTime-this.C.getCurrentTime()||(a=this.o,a=a.o.tk(a),!g.Y(this.C).experiments.o("disable_captions_unknown_requests")&&!a.o[0].duration)||(this.F.contains(a.o[0].ya)||LBa(this,a),this.o=g.Ja(a.o));this.K.start()};
g.h.vU=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status;if(!g.Y(this.C).experiments.o("disable_captions_redirects_redux")){var c=g.CL(a);if(c){a=g.fL(this.A,this.L,{});b=this.A;g.bL(b.A,a,c);b.requestId=a.get("req_id");LBa(this,this.A);return}}b||null===this.J||(this.G?this.J(a.response,1E3*(this.A.o[0].startTime+u4(this.C)),this.A.o[0].ya):this.J(a.responseText,1E3*(this.A.o[0].startTime+u4(this.C)),this.A.o[0].ya));this.B=this.A=null};g.t(i5,e5);g.h=i5.prototype;g.h.hu=function(a,b){this.Wd();var c=MBa(this,a.A);if(c){var d=c.index.Oo(c.index.tf());g.Y(this.C).experiments.o("html5_disable_caption_starttime")||(d-=c.index.Sd(c.index.tf()));d*=1E3;var e=g.Y(this.C).Na;this.D=new h5(new g.LK,this.C,c,function(c,e,l){b(c,a,e,d,l)},e||g.kI(c.info),(0,g.A)(function(){this.D&&this.D.reset();
this.o&&this.o.reset();this.F=!0},this))}};
g.h.oE=function(){var a=this.F;this.F=!1;return a};
g.h.iu=function(a){if(g.Y(this.C).Na)b5(this.A,new g.XH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),b5(this.A,new g.XH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.B.o){var c=this.B.o[b];if(g.oI(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.Y(this.C).experiments.o("html5_manifestless_captions_fmt3_killswitch"))){var d="en",e="English",f=".en";if(c=
c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;b5(this.A,new g.XH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Wd=function(){e5.prototype.Wd.call(this);this.D&&(this.D.dispose(),this.D=null)};
g.h.Ol=function(){return""};
g.h.X=function(){this.Wd();e5.prototype.X.call(this)};g.t(k5,z4);k5.prototype.Ir=function(a){var b=this.H.A;z4.prototype.Ir.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Ga(d,c.A);g.Ga(d,$Ba);var e=c.A;var f=d}iBa(this,c,d)}};
var $Ba={lt:!0};g.t(l5,z4);g.h=l5.prototype;g.h.HE=function(){g.lu(this.da)};
g.h.AU=function(){g.zq(this.element,"ytp-rollup-mode");this.mj(this.sa,!0)};
g.h.Lz=function(){return this.L};
g.h.Kz=function(){return this.H.params.uq*m5(this)};
g.h.mj=function(a,b){this.sa=a;if(m5(this)){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));c=this.L;this.L=0;z4.prototype.mj.call(this,a);d=this.C.offsetWidth+1;this.L=Math.max(NBa(this),c,d);c=this.H.params.uq*m5(this)-this.C.offsetHeight;c!=this.Z&&(b||(0,window.isNaN)(this.Z)||(g.T(this.element,"ytp-rollup-mode"),g.ku(this.da)),g.xh(this.C,"transform",c?"translateY("+c+"px)":""),this.Z=c);z4.prototype.mj.call(this,a)}else z4.prototype.mj.call(this,
a)};g.t(n5,e5);g.h=n5.prototype;g.h.hu=function(a,b){var c=this.Ol(a),d=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.Wd();this.B=g.yE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.iu=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.KA&&(b.asrs=1);d=g.qE(d,b);b=(0,g.A)(function(b){this.B=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.A,e=g.q(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),p=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),E=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
L="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");b5(d,new g.XH({formats:l,format:c,languageCode:n,languageName:p,name:r,kind:u,id:E,is_servable:!0,is_translateable:L,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:r,
is_default:u},this.F[l.languageCode]=l.languageName,this.G.push(new g.WH(l))}a()},this);
this.Wd();this.B=g.yE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Ol=function(a){var b=this.D,c={v:this.C,type:"track",lang:a.A,name:a.F,kind:a.C,fmt:a.B};a.o&&(c.tlang=t4(a));return b=g.qE(b,c)};
g.h.Wd=function(){e5.prototype.Wd.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.Wd();e5.prototype.X.call(this)};g.t(q5,g.DU);g.h=q5.prototype;g.h.X=function(){if(this.G){var a=g.wU(this.K);a&&a.Hj()}else TBa(this,!1);g.DU.prototype.X.call(this)};
g.h.GB=function(){return this.G?!this.B.Fa:this.ia||r5(this)?!0:OBa(this)};
g.h.load=function(a){g.DU.prototype.load.call(this);this.J=this.o.getAudioTrack();if(this.D||a)this.A&&(this.G&&!this.C.experiments.o("disable_native_caption_api")?PBa(this,!0):a?this.WD(a,this.A):3!=this.o.Sa()&&this.D.hu(this.A,(0,g.A)(this.WD,this))),this.A&&this.A!=s5(this)?this.o.xa("captionschanged",s4(this.A)):this.o.xa("onCaptionsTrackListChanged");else{var b;j5(this.B,this.K)?b=new i5(this.B.pa,this.o):this.B.captionTracks.length?b=new f5(this.B):b=new n5(this.B.co,this.B.videoId,this.B.mh||
this.C.mh||g.WO(this.B,"yt:cc_default_lang")||this.C.Ba,this.B.bo);this.D=b;b.iu((0,g.A)(this.dV,this),!0,this.G?"vtt":void 0,this.o.getAudioTrack())}};
g.h.unload=function(){this.G?this.C.experiments.o("disable_native_caption_api")?g.wU(this.K).Hj():this.A&&PBa(this,!1):(this.ha&&g.mu(this.ha),g.tU(this.o,"captions"),this.O=[],this.D&&this.D.Wd(),this.L&&g.qU(this.o,this.L),this.ww());g.DU.prototype.unload.call(this);var a=g.bU(this.o.app);a&&a.C&&g.mP(a.C.B);this.o.xa("captionschanged",{})};
g.h.dV=function(){var a;this.M||OBa(this)?a=t5(this,this.M):r5(this)&&(a=s5(this));if(this.G||this.ia){for(var b=a5(this.D.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.YH(e),srclang:t4(e),id:e.toString()};this.ia||(f.src=this.D.Ol(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}g.wU(this.K).ol(c);(a=g.wU(this.K).oa())&&a.textTracks&&a.textTracks.addEventListener&&!this.C.experiments.o("disable_native_caption_api")&&this.Y.R(a.textTracks,"change",this.eV)}else!this.A&&a&&
v5(this,a),this.o.xa("onCaptionsTrackListChanged"),this.o.xa("onApiChange")};
g.h.eV=function(){for(var a=g.wU(this.K).oa().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a5(this.D.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.A:null)!=b&&v5(this,b,!0)};
g.h.hX=function(){this.C.experiments.o("disable_native_caption_api")?this.loaded&&!this.G&&this.unload():!this.A&&this.G||this.unload()};
g.h.WD=function(a,b,c,d,e){a&&(this.D.oE()&&(this.O=[],g.tU(this.K,"captions"),this.da.Zj()),a=JBa(this.D,a,b,c,d),this.C.experiments.o("debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new w4(c,b,0,"_"+x4++,{Qf:2,
bf:100,wg:0}),a.push(d),e=new v4(c,b,0,d.id,"sq="+e),a.push(e)),g.qU(this.o,a),this.M&&!this.ia&&QBa(this),this.M=!1)};
g.h.NN=function(a){this.O.push(a);this.da.Zj()};
g.h.ON=function(a){g.Va(this.O,a);var b=j5(this.B,this.K)&&this.C.Na;!this.C.experiments.o("disable_remove_displayed_close_caption_cue")&&b&&g.sU(this.o,[a]);this.da.Zj()};
g.h.YV=function(a){if(a instanceof w4){var b=this.U[a.id];b&&b.H!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=RBa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.ba[b]||(this.ba[b]=[]),this.ba[b].push(a)};
g.h.iW=function(){SBa(this,this.Z);this.Z=null};
g.h.QF=function(){this.da.stop();g.ac(this.ba);this.O.sort(g.wQ);var a=this.O;if(this.L){var b=(0,g.Sd)(a,function(a){return-1==this.L.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.YV,this);g.Kb(this.U,function(a,b){this.ba[b]?(a.element.parentNode||g.vU(this.o,a.element,4),a.mj(this.ba[b])):(a.dispose(),delete this.U[b])},this)};
g.h.GE=function(){o5(this,{},!0)};
g.h.Os=function(){var a=w5.qb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.zf?3:a.bold?1:a.zf?2:0,textOpacity:a.textOpacity,windowColor:w5.windowColor,windowOpacity:w5.windowOpacity};var b=p5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Aw=function(a,b){var c={};g.Ga(c,p5(this,"display-settings"));g.Ga(c,a);o5(this,c,b);this.o.V("captionssettingschanged")};
g.h.ww=function(){!this.G&&this.loaded&&(g.Kb(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.QF())};
g.h.wu=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.jd(b,-2,4);this.Aw({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&v5(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.C.Hb&&u5(this,"module-enabled",!!b);break;case "track":if(!this.D)return{};if(b){if(this.G)break;if(!g.Ca(b))break;if(g.$b(b)){v5(this,null,!0);break}var d;c=a5(this.D.A,!0);for(var e=0;e<c.length;e++){var f=c[e];f.A!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
fBa(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||v5(this,d,!0)}else return this.loaded&&this.A&&this.A!=s5(this)?s4(this.A):{};return"";case "tracklist":return this.D?(0,g.I)(a5(this.D.A,!(!b||!b.includeAsr)),function(a){return s4(a)}):[];
case "translationLanguages":return this.D?this.D.G:[];case "displaySettings":d=this.Os();if(g.LM(this.C)&&b&&g.Ca(b))if(b.reset)this.GE();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=UBa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=VBa(b[c],d[c]);break;case "charEdgeStyle":var k=g.k1[b[c]];f[c]=g.ta(k)?k:d[c];break;case "fontSizeIncrement":f[c]=WBa(b[c],d[c]);break;case "fontFamilyOption":k=g.j1[b[c]];f.fontFamily=
g.ta(k)?k:d[c];break;case "fontStyle":k=g.l1[b[c]],f[c]=g.ta(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Aw(f,!0);d=this.Os()}d.fontFamilyOption=g.Owa[d.fontFamily];d.charEdgeStyle=g.Pwa[d.charEdgeStyle];d.fontStyle=g.Qwa[d.fontStyle];return d;case "sampleSubtitles":this.G||void 0==b||TBa(this,!!b);break;case "xmlTrack":b&&this.C.Hb&&(this.G||v5(this,new g.XH({languageName:b.name}),!1,b.xml))}};
g.h.LN=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.C.Hb&&a.push("stickyLoading","xmlTrack");return a};
g.h.MN=function(){var a=this.A;return a?{cc:a.G}:{}};
g.h.GF=function(){this.loaded&&this.A&&this.A!=s5(this)?(u5(this,"module-enabled",!1),this.unload(),r5(this,!0)&&v5(this,s5(this),!1)):v5(this,this.A==s5(this)?t5(this,!0):this.A,!0)};
g.h.uR=function(){var a=this.A==s5(this);r5(this,a)?v5(this,this.o.getAudioTrack().Eo,!1):this.B.captionTracks.length&&(this.loaded&&this.unload(),this.GB()&&(a?v5(this,t5(this),!1):this.load()))};g.zX.captions=q5;})(_yt_player);
